# Generated by Django 3.2.25 on 2024-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('numberOfSongs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50, unique=True)),
                ('album', models.CharField(max_length=50)),
                ('length', models.TimeField()),
                ('playlist_name', models.ManyToManyField(to='zing_it.Playlist')),
            ],
        ),
    ]
