# Generated by Django 3.2.25 on 2024-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist_name',
            field=models.ManyToManyField(related_name='songs', to='zing_it.Playlist'),
        ),
    ]
